### ISSUE TITLE
widgets are overflowing when camera is opened

### ISSUE THREAD

**Issue by parth181195** [gdgbaroda/books2go#14]
![f5e7c46d-373f-4126-9ea0-fddfed82c47b](https://user-images.githubusercontent.com/17850142/45133644-06bbca00-b1b4-11e8-9066-7fb8f06000bb.jpg)
I would suggest wrapping it in expanded or setting height explicitly using the sized box

**Comment by Chintan1193** [comment]
@parth181195 Can you please provide info about device you are testing?

**Comment by parth181195** [comment]
xperia x with android o

**Comment by parth181195** [comment]
sure i will check and get back to you

**Comment by CurosMJ** [comment]
Merging this branch

**Comment by SnehPandya18** [comment]
Merged with commit https://github.com/gdgbaroda/books2go/commit/f775ddc32ccb3fc4dd6cc08cdef9d7abdee6ad9b
