### ISSUE TITLE
Better book capture experience

### ISSUE THREAD

**Issue by mistryhardik** [gdgbaroda/books2go#7]
Edit the menu text (side drawer) to read **Scan a book**

In the current iteration, the camera view SCREEN needs the following changes:

- Edit the title of the screen to say **Scan a book**
- Include a warning text (Light Yellow background with Black text) somewhere on the screen to say **Rotate the object for better results, if detection not as expected**

**Comment by Chintan1193** [comment]
@mistryhardik Changed navigation drawer item name to 'Scan A Book'. Thank you for suggestion. We have made app in portrait mode and handled captured image rotation so no need to add rotation related message in it.
